stages:
  - deploy

pages:
  stage: deploy
  image: python:3.12-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx sphinx_rtd_theme sphinx-subfigure
  script:
    - cd docs && make html
  after_script:
    - mv docs/_build/html/ ./public/
  artifacts:
    paths:
    - public
    expire_in: 120 seconds
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
